version: '3'
services:
  go:
    image: 926330672208.dkr.ecr.ap-northeast-1.amazonaws.com/deploypractice2_go:latest
    build: ./docker
    container_name: deploypractice2
    ports:
      - 3000:3000
    tty: true
    # volimensの記述はFargateではエラーになる
    volumes:
      - .:/go/src
    working_dir: /go/src/app
    command: /bin/bash -c "go run main.go"
