version: '3'
services:
  go:
    build:
      context: ./docker
    container_name: deploypractice2
    ports:
      - 3000:3000
    volumes:
      - .:/go/src
    working_dir: /go/src/app
    tty: true
    # command: /bin/bash -c "go run main.go"
